### ISSUE TITLE
Should the Response object be exposed in ResponseWrapper?

### ISSUE THREAD

**Issue by lynnntropy** [nebkam/fluent-test#4]
It seems unnecessarily restrictive to me to completely prevent access to the underlying `Response` when using the `ResponseWrapper`. `Response` has a lot of useful methods that `ResponseWrapper` doesn't replicate; getting a Response that allows you to use methods such as `isRedirect()` and `isSuccessful()` basically requires bypassing the request builder completely, at which point you might as well use the client directly.

I think it would be good to add a `getResponse()` method to `ResponseWrapper` that allows access to the `Response` object when necessary.

**Comment by nebkam** [comment]
Totally makes sense.
The point of the `ResponseWrapper` was enhancing `Response`, not encapsulation.

Added `ResponseWrapper::getResponse`  in 2.0.2
