### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by shkabo** [nebkam/fluent-test#5]
Is there a plan for this package to support symfony 5 ?

**Comment by nebkam** [comment]
I'm not against it, just didn't have time to test with it.
I welcome any PRs regarding Symfony 5 support :)

**Comment by nebkam** [comment]
Added Symfony 5 support in [3.0.0.](https://github.com/nebkam/fluent-test/releases/tag/3.0.0) since it was a BC break (`Symfony\Bundle\FrameworkBundle\Client` was replaced by `Symfony\Bundle\FrameworkBundle\KernelBrowser` in the Browser Kit Component)
